# Recursion - DP

## 1. Euclidean Algorithm

### if $a = bq + c$, then $GCD(a,b) = GCD(b,r)$

In [12]:
def gcd(a,b):
    if a%b == 0:
        return b
    else:
        return gcd(b,a%b)

In [13]:
gcd(10,3)

1

### Sum of an array using recursive

In [19]:
def arr_sum(a, N):
    if N == 1:
        return a[0]
    else:
        return a[0] + arr_sum(a[1:], len(a[1:]))  

In [20]:
arr_sum([1,2,3], len([1,2,3]))

6

### Max of an array

In [11]:
def arr_max(l):
    if len(l) == 1:
        #print(l[0])
        return l[0]
    else:
        #print(l[1:])
        m =  arr_max(l[1:])
        #print("max",m )
        return m if m > l[0] else l[0]

In [12]:
arr_max([6,1,3,2])

6

### Binary search

In [63]:
def bin(arr, ele ):
    mid = (len(arr)-1)//2

    if arr[mid]== ele:
        return mid
    elif ele < arr[mid]:
        return bin(arr[:mid - 1], ele)
    else:
        return bin(arr[mid+1:],ele)



In [64]:
bin([x for x in range(0,100)],14)

0

In [49]:
5//2

2

# Fibonacci

Run time : 
Overall Upper bound : 
### $O(2^n)$ <br>
The Tight Upper bound : 

### $O(1.618^n)$
aka the golden ratio

In [65]:
def fib(n):
    if n<=2:
        return 1
    return fib(n-1) + fib(n-2)


In [68]:
fib(11)

89

# Fib with DP

Memoization or memoisation is an optimization technique used primarily to speed up computer programs by storing the results of expensive function calls and returning the cached result when the same inputs occur again

Time complexity :  
### $O(N)$ <br>

Space complexity:
### $O(N)$ <br>



In [ ]:
def fib(n,memo = {}):
    if n in memo:
        return memo[n]
    if n<=2:
        return 1
    memo[n] = fib(n-1,memo) + fib(n-2,memo)
    #print(memo)
    return memo[n]


In [ ]:
fib(10)

55

# Fib with DP (Optimised Space - Bottom up)
As we only need the last two number to calculate the next Fibonacci sequence. With this logic in mind, we can use two variable to store the last two Fibonacci sequence.

Time complexity :  
### $O(N)$ <br>

Space complexity:
### $O(1)$ <br>

In [ ]:
def fib(n):

    first = 0
    second = 0
    for i in range(1,n+1):
        if i==1:
            second = 1
        else:
            temp = second
            second = first + second
            first = temp
    return second

In [ ]:
fib(10)

55

## 8.1. Triple Step: 

A child is running up a staircase with n steps and can hop either 1 step, 2 steps, or 3
steps at a time. Implement a method to count how many possible ways the child can run up the
stairs.

[GeeksforGeeks](https://www.geeksforgeeks.org/count-ways-reach-nth-stair-using-step-1-2-3/)


In [94]:
def countWays(n):
    if n < 0:
        return 0
    elif n == 0:
        return 1
    else:
        return countWays(n-1) + countWays(n-2) + countWays(n-3)


In [73]:
for i in range (1,10):
    print(countWays(i))

1
2
4
7
13
24
44
81
149


Roughly $O(3^n)$ : 3 branches

With Memoization:

In [98]:

def countWays(n,memo):
    if n < 0:
        return 0
    elif n == 0:
        return 1
    elif n in memo.keys():
        return memo[n]
    else:
        return countWays(n-1,memo) + countWays(n-2,memo) + countWays(n-3,memo)


In [99]:
countWays(27, {})

8646064

Iteratively : 

In [118]:
def countWays(n):
    if n<1:
        return 0
    res = [0] * (n + 1)
    res[0] = 1
    res[1] = 1
    res[2] = 2
 
    for i in range(3, n + 1):
        res[i] = res[i - 1] + res[i - 2] + res[i - 3]
 
    return res[n]

In [117]:
countWays(5)

13

8.2 ***Robot in a Grid*** 

Imagine a robot sitting on the upper left corner of grid with r rows and c columns.
The robot can only move in two directions, right and down, but certain cells are "off limits" such that
the robot cannot step on them. Design an algorithm to find a path for the robot from the top left to
the bottom right.

8.3 **Magic Index:**
 A magic index in an array A [1... n-1] is defined to be an index such that A[i] =
i. Given a sorted array of distinct integers, write a method to find a magic index, if one exists, in
array A.
FOLLOW UP
What if the values are not distinct?

In [119]:
# Brute force

def magicSlow(l):
    for i,v in enumerate(l):
        if i == v:
            return v
    return -1

In [143]:
import random
magicSlow([random.randint(0,10) for i in range(10)])

1

In [144]:
# Recursive 

def magic_index(array, min_index=0, max_index=None):
    if max_index is None:
        max_index = len(array) - 1

    if max_index < min_index:
        return -1

    mid = (max_index + min_index) // 2
    if array[mid] == mid:
        return mid
    if array[mid] < mid:
        return magic_index(array, mid + 1, max_index)
    if array[mid] > mid:
        return magic_index(array, min_index, mid - 1)

In [146]:
 n = 100
 steps = []
 steps[n]

IndexError: list index out of range

## 62. Unique Paths

![image](https://assets.leetcode.com/uploads/2018/10/22/robot_maze.png)


```py
# Initialize a m*n array of identical element
d = [[1] * n for _ in range(m)]
```




In [152]:
class Solution:
    def uniquePaths(self, r: int, c: int) -> int:
        if r == 1 or c ==1:
            return 1
        return  self.uniquePaths(r-1,c) + self.uniquePaths(r,c-1)
        

In [165]:
c = Solution()
c.uniquePaths(10,5)

# Is also same as (10+5 -2)C(5-1) or (10+5 -2)C(10-1)

715

In [159]:
class Solution:
    def uniquePaths(self, r: int, c: int) -> int:
        matrix = [ [ 1 for i in range(c) ] for j in range(r) ]
        for ci in range(1,len(matrix)):
            for ri in range(1,len(matrix[ci])):
                matrix[ci][ri] = matrix[ci-1][ri] +  matrix[ci][ri-1] 
        return matrix[-1][-1]

In [163]:
c = Solution()
c.uniquePaths(10,10)

48620

What is the solution using combinatrics?

# 198. House Robber

In [202]:
# Recursive
class Solution:
    def rob(self, nums):
        return self.robFrom(0,nums)

    def robFrom(self, i, nums):
        if i>= len(nums):
            return 0
        ans = max(self.robFrom(i + 1, nums), self.robFrom(i + 2, nums) + nums[i])
        return ans

In [212]:
import random
c = Solution()
c.rob([random.randint(1, 90) for i in range(30) ])

783

In [213]:
# Top-down Memoization
class Solution:
    def rob(self, nums):
        self.memo = {}
        return self.robFrom(0,nums)

    def robFrom(self, i, nums):
        if i>= len(nums):
            return 0
        if i in self.memo:
            return self.memo[i]
        ans = max(self.robFrom(i + 1, nums), self.robFrom(i + 2, nums) + nums[i])
        
        self.memo[i] = ans
        return ans


Time Complexity: O(N)
Space Complexity: O(N)


In [214]:
import random
c = Solution()
c.rob([random.randint(1, 90) for i in range(30) ])

838

In [199]:
# Bottom - up DP
def rob(nums):
        if len(nums) ==1:
            return nums[0]
        
        if nums == 2:
            return max(nums[0], nums[1])
        
        dp = [0 for i in range(len(nums))]
        dp[0] = nums[0]
        dp[1] = max(nums[0], nums[1])
        for i in range(2,len(nums)):
            dp[i] = max(nums[i]+dp[i-2], dp[i-1])
        return dp[-1]

In [217]:
rob([random.randint(1, 90) for i in range(100) ])

2677

Q) Two Sum

In [230]:
def twoSum(nums, target):
        h = {}
        for  i,v in enumerate(nums):
            h[v] = i
        for i in range(len(nums)):
            c = target - nums[i]
            if c in h and h[c]!=i:
                print(h)
                return [i,h[c]]

Q) Find all permutation of a given string

In [3]:
# Initialising string
ini_str = "abc"

# Printing initial string
print("Initial string", ini_str)

# Finding all permutation
result = []

def permute(data, i, length):
    if i == length:
        result.append(''.join(data) )
        #print(result)
    else:
        for j in range(i, length):
            # swap
            #print("Before Swapping", data[i], data[j] )
            data[i], data[j] = data[j], data[i]
            #print("After Swapping", data[i], data[j] )
            
            permute(data, i + 1, length)
            data[i], data[j] = data[j], data[i]
            
permute(list(ini_str), 0, len(ini_str))

# Printing result
print("Resultant permutations", str(result))


Initial string abc
Resultant permutations ['abc', 'acb', 'bac', 'bca', 'cba', 'cab']


118. Pascal's Triangle

In [7]:
def generate(numRows):
    res = [[1]]
    for i in range(1,numRows):
        temp = [0] + res[-1] + [0]
        row = []
        for j in range(len(res[-1])+1):
            row.append(temp[j]+temp[j+1])
        res.append(row)

    return res


In [14]:
print(*generate(5), sep = '\n')

[1]
[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]


1137. N-th Tribonacci Number

In [17]:
def tribonacci(n: int) -> int:
    dp = [0 for i in range(n+1)]
    if n == 0:
        return 0
    elif n == 2 or n == 1:
        return 1
    dp[0] = 0
    dp[1] = 1
    dp[2] = 1
    for i in range(3, n+1):
        dp[i] = dp[i-1] + dp[i-2] + dp[i-3]
    return dp[n]

In [18]:
tribonacci(6)

13

53. Maximum Subarray (Kadane's Algorithm)

In [21]:
def maxSubArray(nums) -> int:
    # Kadane's algorithm
    maxS = nums[0]
    curS = maxS
    for i in range(1,len(nums)):
        curS = max(nums[i], curS+nums[i])
        maxS = max(maxS, curS)
    return maxS

In [20]:
maxSubArray([1,-2,17])

17

In [23]:
import numpy as np
x = np.arange(4)

x

array([0, 1, 2, 3])

In [34]:
xx = x.reshape(4,1)

In [32]:
xx

array([[0],
       [1],
       [2],
       [3]])

In [35]:
y = np.ones(5)

In [36]:
y

array([1., 1., 1., 1., 1.])

In [37]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
(4,)

(4,)

In [40]:
x.shape

(4,)

In [1]:
!pip install pymc3

     |████████████████████████████████| 869 kB 7.7 MB/s            
     |████████████████████████████████| 86 kB 12.4 MB/s            
     |████████████████████████████████| 1.8 MB 15.9 MB/s            
  Preparing metadata (setup.py) ... done
     |████████████████████████████████| 1.6 MB 12.7 MB/s            
     |████████████████████████████████| 4.2 MB 13.2 MB/s            
     |████████████████████████████████| 835 kB 7.1 MB/s            
     |████████████████████████████████| 213 kB 9.0 MB/s            
  Created wheel for theano-pymc: filename=Theano_PyMC-1.1.2-py3-none-any.whl size=1529946 sha256=014311aa2e0f82b591ae9e11aa706793dd2aa6e0a204f7795ec0e9070f53d75d
  Stored in directory: /Users/shreyasprasad/Library/Caches/pip/wheels/0e/41/d2/82c7b771236f987def7fe2e51855cce22b270327f3fedec57c
Successfully built theano-pymc
